services:
  x15015556_erc20:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - joeys_network
networks:
  joeys_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.60.0.0/24